# Generated by Django 3.2.8 on 2021-11-05 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccountapp', '0002_alter_client_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankaccountapp.client')),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
